version: "3.8"

services:
  db:
    image: postgres:15
    networks:
      - back
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis
    networks:
      - back
    env_file:
      - .env
    ports:
      - "6379:6379"


  backend:
    build: ./backend
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    networks:
      - back
    volumes:
      - ./backend/:/usr/src/app/
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/protected
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - RUN_MIGRATIONS=0
      - RUN_MIGRATE=1
      - FLUSH_DATABASE=0
      - DJANGO_SETTINGS_MODULE=backend.settings
      - RUN_COLLECTSTATIC=0
    env_file:
      - .env
    depends_on:
      - db
      - redis

  smtp:
    build: ./smtp_server
    network_mode: host
    env_file:
      - .env

  nginx:
    build: ./nginx
    networks:
      - front
      - back
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/protected
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

    ports:
      - '80:80'
      - '443:443'
    env_file:
      - .env
    depends_on:
      - backend
    restart: always



volumes:
  database:
  static_volume:
  media_volume:
  ssl_volume:

networks:
  front:
  back:
